module.exports = {
"INFORMATION_FETCHED" : "Information fetched successfully.",
"INFORMATION_UPDATED" : "Information updated successfully.",

"ASSESSMENT_FETCHED" : "Assessment fetched successfully",
"PENDING_ASSESSMENT" : "Pending Assessments",
"COMPLETED_ASSESSMENT" : "Completed Assessments",
"ASSESSMENT_BLOCK_FOR_RATING" : "Sorry! This could be because the assessment has been blocked. Resolve conflicts to proceed further.",

"CONFIGURATIONS_NOT_FOUND" : "No configurations available for given params.",
"CONFIGURATIONS_FETCHED" : "Configurations fetched successfully.",

"ENTITY_ADDED" : "Entity information added successfully.",
"ENTITIES_NOT_UPDATE" : "Not all entities are updated.",
"ENTITIES_UPDATED" : "Entities updated successfully.",
"ENTITY_REMOVED" : "Entity Removed successfully.",
"ENTITY_FETCHED" : "Entities fetched successfull",
"ENTITY_NOT_FOUND" : "No entitiy found",
"ENTITY_PROFILE_FORM_NOT_FOUND" : "No entity profile form found.",
"ENTITY_ID_NOT_FOUND" : "Entity Id is not found",
"ENTITY_LIST" : "List of entities fetched successfully",
"ENTITY_SOLUTION_USER_NOT_FOUND" : "Entity Id or User or solution is not present",
"ENTITY_INFORMATION_NOT_INSERTED" : "Some entity information was not inserted!",
"ENTITIES_FILE_NOT_FOUND" : "Csv file for entities should be selected",
"ENTITY_MAP_FILE_NOT_FOUND" : "Csv file for entity map should be selected",

"ENTITY_ASSESSOR_FILE_NOT_FOUND" : "Csv file for entity assessor should be selected",

"INVALID_ENTITY_TYPE" : "Invalid entity type.",
"ENTITY_TYPE_REQUIRED" : "Entity type is required.",
"ENTITY_TYPES_FETCHED" : "Entity types fetched successfully.",
"ENTITY_TYPE_INDEX" : "Entity type index created successfully.",

"ASSESSOR_CREATED" : "Assessor record created successfully.",
"ASSESSOR_LIST" : "List of assessors fetched successfully",
"ASSESSOR_NOT_FOUND" : "No assessor found.",

"FILES_NAME_NOT_GIVEN" : "File names not given.",
"URL_GENERATED" : "URLs generated successfully.",

"FRAMEWORK_NOT_FOUND" : "No framework found",
"REQUIRED_FRAMEWORK_EXTERNALID" : "External Id for framework is required",
"REQUIRED_FRAMEWORK_NAME" : "Name for framework is required",
"REQUIRED_FRAMEWORK_DESCRIPTION" : "Description for framework is required",
"REQUIRED_ENTITY_TYPE_FOR_FRAMEWORK" : "Entity Type for framework is required",
"FRAMEWORK_EXISTS" : "Framework already exists",
"FRAMEWORK_INSERTED" : "Framework inserted successfully.",
"FRAMEWORK_UPDATED" : "Framework updated successfully.",

"PROGRAM_NOT_FOUND" : 'No program found.',
"ROGRAM_EXISTS" : "Program already exists",
"PROGRAM_IMPORTED" : "Program imported successfully.",
"PROGRAM_LIST" : "Program information list fetched successfully.",
"PROGRAM_ID_REQUIRED" : "Program id is required",

"SOLUTION_UPDATED" : "Solution updated successfully",
"SOLUTION_NOT_FOUND" : "No solution found.",
"SOLUTION_EXISTS" : "Solution already exists",
"SOLUTION_IMPORTED" : "Solution imported successfully.",
"SOLUTION_FETCHED" : "Solutions fetched successfully",
"SOLUTION_ID_NOT_FOUND" : "Solution Id is not found",
"DUPLICATE_SOLUTION" : "Duplicate Solution generated.",
"MAP_SOLUTION_TO_PROGRAM" : "Solution generated and mapped to the program.",

"CRITERIA_FILE_NOT_FOUND" : "Csv file for criterias should be selected",
"CRITERIA_RUBRIC_UPDATE" : "Criteria rubric updated successfully.",
"CRITERIA_INSERTED" : "Criterias inserted successfully.",
"CRITERIA_RATING" : "Crtieria rating completed successfully",
"CRITERIA_NOT_FOUND" : "Criteria is not found",
"INVALID_CRITERIA_ID" : "Invalid criteria external ID.",
"CRITERIA_QUESTION_NOT_FOUND" : "No criteria question found.",

"QUESTION_INSERTED" : "Questions inserted successfully.",
"QUESTION_NOT_FOUND" : "No question found",

"INSIGHTS_NOT_FOUND" : "No insights found",
"INSIGHTS_FETCHED" : "Insights report fetched successfully.",
"HIGH_LEVEL_INSIGHTS" : "High Level Insights report fetched successfully.",

"OBSERVATION_META_FETCHED" : "Observation meta fetched successfully.",
"OBSERVATION_CREATED" : "Observation created successfully.",
"OBSERVATION_LIST" : "Observation list fetched successfully",
"OBSERVATION_NOT_PUBLISHED" : "Observation not published.",
"OBSERVATION_NOT_FOUND" : "No observation found.",
"OBSERVATION_MARKED_COMPLETE" : "Observation marked as completed.",
"OBSERVATION_ALREADY_COMPLETED" : "Observation already completed",
"OBSERVATION_UPDATED" : "Observation successfully updated.",
"OBSERVATION_DELETED" : "Observation deleted successfully.",
"OBSERVATION_FETCHED" : "Observation fetched successfully.",
"OBSERVATION_RATING" : "Observation rating completed successfully.",
"OBSERVATION_AUTO_RATING_SUCCESS" : "Observation Auto Rating Successful - ",
"OBSERVATION_AUTO_RATING_FAILED" : "Observation Auto Rating FAILED - ",
"PENDING_OBSERVATION" : "Pending Observations",
"COMPLETED_OBSERVATION" : "COmpleted Observations",
"ERROR_CREATING_OBSERVATION" : "Some error while creating observation solution.",
"INVALID_OBSERVATION_ENTITY_ID" : "Invalid observation or entity id.",
"NO_PENDING_COMPLETED_OBSERVATIONS" : "No Pending or Completed Observations found",

"OBSERVATION_SOLUTION" : "Observation Solution generated.",

"OBSERVATION_SUBMISSION_CREATED" : "Observation submission created successfully",
"OBSERVATION_SUBMISSION_CHECK" : "Observation submission check completed successfully",
"OBSERVATION_SUBMISSION_DELETED" : "Observation submission deleted successfully",
"OBSERVATION_SUBMISSION_ID_NOT_FOUND" :"No observation submission id found",
"OBSERVATION_SUBMISSSION_NOT_FOUND" : "No observation submission found",

"SUBMISSION_NOT_FOUND" : "No submission found.",
"SUBMISSION_FOUND" : "submission found.",

"PARENT_INTERVIEW_COMPLETED" : "Parent Interview completed successfully.",
"PARENT_INTERVIEW_SUBMITTED" : "Parent interview submitted successfully.",
"PARENT_INFORMATION_NOT_FOUND" : "No parent information found.",
"PARENT_INTERVIEW_FETCHED" : "Parent interview response fetched successfully.",
"PARENT_INTERVIEW_FAILED" : "Failed to complete parent interview.",
"PARENT_NOT_FOUND" : "No parent found",

"USER_EXTENSION_NOT_FOUND" : "User Extension not found .",
"USER_EXTENSION_ENTITIES_FETCHED" : "User Extension entities fetched successfully",
"USER_EXTENSION_FETCHED" : "User profile fetched successfully.",

"SUBMISSION_CHECK" : "Submission check completed successfully",
"SUBMISSION_STATUS_FETCHED" : "Submission status fetched successfully",
"FOUND_SUBMISSION" : "Submission found",
"SUBMISSION_COMPLETED" : "Submission completed successfully",
"SUBMISSION_NUMBER_FETCHED" : "Submission Number fetched successfully.",
"SUBMISSION_STATUS_NOT_COMPLETE" : "Submission status is not completed",
"SUBMISSION_ID_NOT_FOUND" : "No submission id found",
"SUBMISSION_RATING_COMPLETED" : "Submission rating completed successfully.",
"SUBMISSION_AUTO_RATING_SUCCESS" : "Submission Auto Rating Successful - ",
"SUBMISSION_AUTO_RATING_FAILED" : "Submission Auto Rating FAILED - ",

"GENERAL_QUESTION_SUBMITTED" : "General question submitted successfully.",
"GENERAL_QUESTION_FAILED" : "Failed to submit general questions",
"ANSWER_MERGED" : "Answers merged successfully",

"ECM_REQUIRED" : "Ecm is required",
"ECM_NOT_EXIST" : "Ecm doesnot exists",
"ECM_RESET" : "ECM Reset successfully",
"DUPLICATE_ECM_SUBMISSION" : "Duplicate evidence method submission detected.",
"ALL_ECM_NOT_SUBMITTED" : "All ECM are not submitted",
"ALL_ECM_NOT_COMPLETED" : "Sorry! All evidence methods have to be completed to enable ratings.",

"NOTIFICATIONS_PUSHED_TO_KAFKA" : "All notifications pushed to Kafka.",
"NOTIFICATION_PUSHED_TO_KAFKA" : "Notifications successfully pushed to Kafka.",

"FEEDBACK_ERROR" : "Atleast one evidence method has to be completed before giving feedback.",
"FEEDBACK_SUBMITTED" : "Feedback submitted successfully.",

"USER_ENTITY_ID" : "User entity id.",
"USER_ID_REQUIRED_CHECK" : "User ID is required.",

"INVALID_PARAMETER" : "Invalid parameters.",
"INVALID_TYPE" : "Type is invalid",

"MISSING_CLOUD_STORAGE_PROVIDER" : "Cloud storage provider not given.",
"INVALID_CLOUD_STORAGE_PROVIDER" : "Invalid Cloud storage provider.",

"FAILED_PRE_SIGNED_URL" : "Failed to generate pre signed URLs.",
"FAILED_SIGNED_URL" : "Failed to generated Signed URL.",


"REPORTS_FILTER" : "Reports filter fetched successfully.",
"MANAGER_PROFILE" : "Manager profile fetched successfully.",
"NO_DATA_FOUND" : "No data found for given params.",
"BODY_NOT_EMPTY" : "Body should not be empty.",
"ERROR_CREATING_DUPLICATE" : "Some error while creating duplicate solution.",
"STATIC_LINKS_FETCHED" : "Static Links fetched successfully.",
"FILE_DATA_MISSING" : "File or data is missing.",
"ALREADY_COMPLETED" : "Already completed.",
"DUMMY_RATE" : "Dummy Crtieria rating completed successfully",
"INSUBMITTED_FALSE" : "isSubmitted False",
"VALID_INVALID_RESPONSE" : "Invalid new or old response!",
"DONE" : "Done",
"NOT_Done" : "Not Done",
"USER_ROLES_FETCHED" : "User roles fetched successfully.",
"SOMETHING_WRONG_INSERTED_UPDATED" : "Something went wrong, not all records were inserted/updated.",
"INVALID_MAPPING_DATA" : "Invalid mapping data",
"MISSING_ENTITYID_ENTITYTYPE_ENTITYTYPEID" : "EntityTypeId or entityType or entityId is not found",
"CREATE_INDEX" : "Index successfully created.",
"INDEX_NOT_CREATED" : "Something went wrong! Couldn't create the index.",
"WRONG_ACTION" : "wrong action" ,
"INVALID_USER_ID" : "Invalid user id.",
"MISSING_ASSESSOR_LEAD_ASSESSOR" : "No LEAD_ASSESSOR or ASSESSOR Found",
"MISSING_NAME_EXTERNALID" : "Name or externalId is missing ",
"THEME_SUBTHEME_FAILED" : "Failed to find a matching theme or sub-theme with the same external id and name.",
"CRITERIA_WEIGHTAGE_NOT_UPDATED" : "Something went wrong! Not all criteira weightage were updated.",
"INVALID_ROLE_CODE" : "Invalid role code.",
"INVALID_ENTITY_OPERATION" : "Invalid entity operation.",
"INVALID_ENTITY_ID" : "Invalid entity id.",
"KEYCLOAK_USER_ID" : "Keycloak user ID is mandatory.",
"MISSING_EMAIL_RECIPIENTS" : "Email Recipients Missing.",
"NOT_FOUND" : "Not found!",
"UNAUTHORIZED" : 'Unauthorized.',
"SOMETHING_WENT_WRONG" : "Something went wrong!",
"FEEDBACK_FORM_FETCHED" : "Feedback from fetched successfully.",
"CREATED_BY_NOT_FOUND" : "Created by is not found",
"ZONE_LIST" : "List of zones fetched successfully",
"UPLOADED_REQUEST" : "Uploaded request submitted successfully",
"INVALID_REQUEST_ID" : "Invalid request ID.",
"FETCH_REQUEST" : "Request document fetched successfully.",

"THEMES_DATA_NOT_FOUND" : "Csv for themes data could not be found"

}